export interface Car {
  id: number;
  make: string;
  model: string;
  year?: number;
  vin: string;
  license_plate: string;
  color?: string;
  owner?: string;
  trim?: string;
  engine?: string;
  transmission?: string;
  drivetrain?: string;
  fuel_type?: string;
  purchase_date?: string;
  purchase_price?: number;
  purchase_mileage?: number;
  current_mileage?: number;
  notes?: string;
  is_archived?: boolean;
  photo_filename?: string;
  horsepower?: number;
  torque_lbft?: number;
  zero_to_100_s?: number;
  top_speed_kmh?: number;
  weight_kg?: number;
  fuel_city?: string;
  fuel_highway?: string;
  fuel_tank_l?: number;
  oil_capacity_l?: number;
  oil_type?: string;
  coolant_capacity_l?: number;
  tire_size_summer?: string;
  tire_size_winter?: string;
  front_disk_mm?: number;
  rear_disk_mm?: number;
  doors?: number;
  body_class?: string;
  cylinders?: number;
  displacement_l?: number;
  plant_country?: string;
  service_records: import('./service').ServiceRecord[];
  scheduled_maintenance: import('./maintenance').ScheduledMaintenance[];
  car_notes: import('./note').CarNote[];
}

export interface CarSummary {
  id: number;
  make: string;
  model: string;
  year?: number;
  vin: string;
  license_plate: string;
  color?: string;
  owner?: string;
  trim?: string;
  current_mileage?: number;
  service_count: number;
  total_spent: number;
  last_service_date?: string;
  next_due_date?: string;
  is_archived?: boolean;
  photo_filename?: string;
}

export interface CarCreate {
  make: string;
  model: string;
  year?: number;
  vin: string;
  license_plate: string;
  color?: string;
  owner?: string;
  trim?: string;
  engine?: string;
  transmission?: string;
  drivetrain?: string;
  fuel_type?: string;
  purchase_date?: string;
  purchase_price?: number;
  purchase_mileage?: number;
  current_mileage?: number;
  notes?: string;
  is_archived?: boolean;
  photo_filename?: string;
  horsepower?: number;
  torque_lbft?: number;
  zero_to_100_s?: number;
  top_speed_kmh?: number;
  weight_kg?: number;
  fuel_city?: string;
  fuel_highway?: string;
  fuel_tank_l?: number;
  oil_capacity_l?: number;
  oil_type?: string;
  coolant_capacity_l?: number;
  tire_size_summer?: string;
  tire_size_winter?: string;
  front_disk_mm?: number;
  rear_disk_mm?: number;
  doors?: number;
  body_class?: string;
  cylinders?: number;
  displacement_l?: number;
  plant_country?: string;
}

export type CarUpdate = Partial<CarCreate>;
